app:
  name: "blog"
  version: "1.0.0"
  port: 8080

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "blog_db"

jwt:
  secret: "a93f6e8bd44c24f6bc59f15ea69e4f5e6c1a16ee2dc0498ff2b02aa6ce1b7a09"
